-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ./hyprland/env.conf -> requires manual conversion
local env = require("hyprland.env")
-- TODO: convert ./hyprland/env.conf to .lua and use require()

-- source = ./hyprland/keybinds.conf -> requires manual conversion
local keybinds = require("hyprland.keybinds")
-- TODO: convert ./hyprland/keybinds.conf to .lua and use require()

-- source = ./hyprland/general.conf -> requires manual conversion
local general = require("hyprland.general")
-- TODO: convert ./hyprland/general.conf to .lua and use require()

-- source = ./hyprland/rules.conf -> requires manual conversion
local rules = require("hyprland.rules")
-- TODO: convert ./hyprland/rules.conf to .lua and use require()

-- source = ./hyprland/colors.conf -> requires manual conversion
local colors = require("hyprland.colors")
-- TODO: convert ./hyprland/colors.conf to .lua and use require()

-- source = ./hyprland/execs.conf -> requires manual conversion
local execs = require("hyprland.execs")
-- TODO: convert ./hyprland/execs.conf to .lua and use require()

--###############

--## MONITORS ###

--###############

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "",
    mode     = "1920x1080@60",
    position = "-1920x0",
    scale    = 1,
})
