-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- exec = export SLURP_ARGS='-d -c FFDAD4BB -b 673B3444 -s 00000000'

hl.config({
    general = {
        col = {
            active_border = "rgba(F7DCDE39)",
            inactive_border = "rgba(A58A8D30)",
        },
    },
})

hl.config({
    misc = {
        background_color = "rgb(000000)",
    },
})

hl.window_rule({
    name  = "match_pin_border_col",
    match = {
	pin = true,
    },
    border_color = "rgba(FFB2BCAA) rgba(FFB2BC77)",
    -- TODO: review rule: "match:pin border_color rgba(FFB2BCAA) rgba(FFB2BC77)"
})
