-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- env = COLOR_SCHEME, prefer-dark

-- env = GTK_THEME, Orchis-Grey-Dark

-- env = GTK2_RC_FILES, ~/.local/share/themes/Orchis-Grey/gtk-2.0/gtkrc

-- env = QT_STYLE_OVERRIDE, Adwaita-Dark

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("HYPERCURSOR_THEME", "Afterglow-cursors")

-- ----------- NVIDIA ------------

--env = LIBVA_DRIVER_NAME,nvidia

--env = __GLX_VENDOR_LIBRARY_NAME,nvidia

--env = NVD_BACKEND,direct
