# exec-once = hypridle
# exec-once = ashell
exec-once = qs -c noctalia-shell
# exec-once = swaync
# exec-once = hyprpaper

exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
# exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps 

