-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    input = {
        kb_layout = "us,il",
        kb_options = "grp:alt_shift_toggle",
        numlock_by_default = true,
        repeat_delay = 250,
        repeat_rate = 35,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
            scroll_factor = 0.5,
        },
        special_fallthrough = true,
        follow_mouse = 1,
        mouse_refocus = false,
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.config({
    gestures = {
        --    workspace_swipe = true
        workspace_swipe_distance = 700,
        --    workspace_swipe_fingers = 4
        workspace_swipe_cancel_ratio = 0.2,
        workspace_swipe_min_speed_to_force = 5,
        workspace_swipe_direction_lock = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_create_new = true,
    },
})

hl.config({
    general = {
        -- Gaps and border
        gaps_in = 4,
        gaps_out = 5,
        gaps_workspaces = 50,
        border_size = 1,
        -- Fallback colors
        resize_on_border = true,
        no_focus_fallback = true,
        layout = "dwindle",
        --focus_to_other_workspaces = true # ahhhh i still haven't properly implemented this
        allow_tearing = true,
        -- This just allows the `immediate` window rule to work
        col = {
            active_border = "rgba(0DB7D4FF)",
            inactive_border = "rgba(31313600)",
        },
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = false,
    },
})

hl.config({
    decoration = {
        rounding = 20,
        blur = {
            enabled = true,
            xray = true,
            special = false,
            new_optimizations = true,
            size = 14,
            passes = 4,
            brightness = 1,
            noise = 0.01,
            contrast = 1,
            popups = true,
            popups_ignorealpha = 0.6,
        },
        -- Shadow
        shadow = {
            enabled = true,
            range = 20,
            offset = "0 2",
            render_power = 4,
            color = "rgba(0000002A)",
        },
        -- Window Opacities
        -- active_opacity = 1
        -- inactive_opacity = 1
        -- fullscreen_opacity = 1
        -- Shader
        -- screen_shader = ~/.config/hypr/shaders/nothing.frag
        -- screen_shader = ~/.config/hypr/shaders/vibrance.frag
        -- Dim
        dim_inactive = false,
        dim_strength = 0.1,
        dim_special = 0,
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Animation curves
        -- use with .2s duration
        -- Animation configs
        -- animation = layers, 1, 2, md3_decel, slide
        -- animation = workspaces, 1, 2.5, softAcDecel, slide
        -- animation = workspaces, 1, 7, menu_decel, slidefade 15%
        -- animation = specialWorkspace, 1, 3, md3_decel, slidefadevert 15%
    },
})

hl.config({
    misc = {
        vrr = 1,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        enable_swallow = false,
        swallow_regex = "(foot|kitty|allacritty|Alacritty)",
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        -- new_window_takes_over_fullscreen = 2
        allow_session_lock_restore = true,
        initial_workspace_tracking = false,
    },
})
