-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local scripts = "~/.config/hypr/scripts"

local terminal = "ghostty"

local mainMod ="SUPER"

-- Lines ending with `# [hidden]` won't be shown on cheatsheet

-- Lines starting with #! are section headings

hl.bind(mainMod .. " + " .. "XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"), { locked = true })

-- [hidden]

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

-- [hidden]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%"), { locked = true })

-- [hidden]

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

-- [hidden]

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

-- [hidden]

-- hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true })

-- hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true })


hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

-- [hidden] # In case you're from i3 or its Wayland clone

--#! Actions

-- Screenshot, Record, OCR, Color picker, Clipboard history

-- bind = mainMod, V, exec, pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy # Clipboard history >> clipboard

hl.bind(mainMod .. " + " .. "Period", hl.dsp.exec_cmd("pkill fuzzel || ~/.local/bin/fuzzel-emoji"))

-- Pick emoji >> clipboard

hl.bind("CTRL+SHIFT+ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("pkill wlogout || wlogout -p layer-shell"))

-- [hidden]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh --freeze copy area"))

-- Screen snip

hl.bind(mainMod .. "+SHIFT+ALT" .. " + " .. "S", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| satty -f-"))

-- Screen snip >> edit

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t"))

-- Color picker

hl.bind(mainMod .. "+SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Pick color (Hex) >> clipboard

-- Fullscreen screenshot

hl.bind("Print", hl.dsp.exec_cmd("grim-| wl-copy"), { locked = true })

-- Screenshot >> clipboard

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && ~/.config/ags/scripts/grimblast.sh copysave screen ~/Pictures/Screenshots/Screenshot_ \"$(date '+%Y-%m-%d_%H.%M.%S')\".png"), { locked = true })

-- Screenshot >> clipboard & file

--#! Session

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("loginctl lock-session"))

-- Lock

hl.bind(mainMod .. "+SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("loginctl lock-session"))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("sleep 0.1 && systemctl suspend || loginctl suspend"), { locked = true })

-- Suspend system

hl.bind("CTRL+SHIFT+ALT+" .. mainMod .. " + " .. "Delete", hl.dsp.exec_cmd("systemctl poweroff || loginctl poweroff"))

-- [hidden] Power off

--!

--#! Window management

-- Focusing

--/# bind = mainMod, ←/↑/→/↓,, # Move focus in direction

hl.bind(mainMod .. " + " .. "Left", hl.dsp.focus({ direction = "left" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "Right", hl.dsp.focus({ direction = "right" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "Up", hl.dsp.focus({ direction = "up" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "Down", hl.dsp.focus({ direction = "down" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "BracketLeft", hl.dsp.focus({ direction = "left" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "BracketRight", hl.dsp.focus({ direction = "right" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. "+SHIFT+ALT" .. " + " .. "Q", hl.dsp.exec_cmd("hyprctl kill"))

-- Pick and kill a window

--#! Window arrangement

--/# bind = mainMod+SHIFT, ←/↑/→/↓,, # Window: move in direction

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Left", hl.dsp.window.move({ direction = "l" }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Right", hl.dsp.window.move({ direction = "r" }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Up", hl.dsp.window.move({ direction = "u" }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Down", hl.dsp.window.move({ direction = "d" }))

-- [hidden]

-- Window split ratio

--/# binde = mainMod, +/-,, # Window: split ratio +/- 0.1

hl.bind(mainMod .. " + " .. "Minus", hl.dsp.layout("splitratio", -0.1))

-- [hidden]

hl.bind(mainMod .. " + " .. "Equal", hl.dsp.layout("splitratio", "+0.1"))

-- [hidden]

hl.bind(mainMod .. " + " .. "Semicolon", hl.dsp.layout("splitratio", -0.1))

-- [hidden]

hl.bind(mainMod .. " + " .. "Apostrophe", hl.dsp.layout("splitratio", "+0.1"))

-- [hidden]

-- Positioning mode

hl.bind(mainMod .. "+ALT" .. " + " .. "Space", hl.dsp.window.float())

-- hl.bind(mainMod .. "+ALT" .. " + " .. "F", hl.dsp.window.fullscreen_state("0 3"))

-- Toggle fake fullscreen

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "D", hl.dsp.window.fullscreen())

--!

--#! Workspace navigation

-- Switching

--/# bind = mainMod, Hash,, # Focus workspace # (1, 2, 3, 4, ...)

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

--/# bind = mainMod, Scroll ↑/↓,, # Workspace: focus left/right

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "+1" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = -1 }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "r+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "r-1" }))

-- [hidden]

--/# bind = CTRL+mainMod, ←/→,, # Workspace: focus left/right

hl.bind("CTRL+" .. mainMod .. " + " .. "Right", hl.dsp.focus({ workspace = "r+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "Left", hl.dsp.focus({ workspace = "r-1" }))

-- [hidden]

--/# bind = CTRL+mainMod+ALT, ←/→,, # Workspace: focus non-empty left/right

hl.bind("CTRL+" .. mainMod .. "+ALT" .. " + " .. "Right", hl.dsp.focus({ workspace = "m+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. "+ALT" .. " + " .. "Left", hl.dsp.focus({ workspace = "m-1" }))

-- [hidden]

--/# bind = mainMod, Page_↑/↓,, # Workspace: focus left/right

hl.bind(mainMod .. " + " .. "Page_Down", hl.dsp.focus({ workspace = "+1" }))

-- [hidden]

hl.bind(mainMod .. " + " .. "Page_Up", hl.dsp.focus({ workspace = -1 }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "Page_Down", hl.dsp.focus({ workspace = "r+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "Page_Up", hl.dsp.focus({ workspace = "r-1" }))

-- [hidden]

--# Special

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special(nil))

hl.bind(mainMod .. " + " .. "mouse:275", hl.dsp.workspace.toggle_special(nil))

--#! Workspace management

-- Move window to workspace mainMod + ALT + [0-9]

--/# bind = mainMod+ALT, Hash,, # Window: move to workspace # (1, 2, 3, 4, ...)

hl.bind(mainMod.. " + ".. "ALT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

-- [hidden]

hl.bind(mainMod.." + " .. "ALT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. "+SHIFT" .. " + " .. "Up", hl.dsp.window.move({ workspace = "special" }, { follow = false }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. "+SHIFT" .. " + " .. "Right", hl.dsp.window.move({ workspace = "r+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. "+SHIFT" .. " + " .. "Left", hl.dsp.window.move({ workspace = "r-1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "BracketLeft", hl.dsp.focus({ workspace = -1 }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "BracketRight", hl.dsp.focus({ workspace = "+1" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "Up", hl.dsp.focus({ workspace = "r-5" }))

-- [hidden]

hl.bind("CTRL+" .. mainMod .. " + " .. "Down", hl.dsp.focus({ workspace = "r+5" }))

-- [hidden]

--/# bind = mainMod+SHIFT, Scroll ↑/↓,, # Window: move to workspace left/right

hl.bind(mainMod .. "+SHIFT" .. " + " .. "mouse_down", hl.dsp.window.move({ workspace = "r-1" }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "mouse_up", hl.dsp.window.move({ workspace = "r+1" }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. "mouse_down", hl.dsp.window.move({ workspace = -1 }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. "mouse_up", hl.dsp.window.move({ workspace = "+1" }))

-- [hidden]

--/# bind = mainMod+SHIFT, Page_↑/↓,, # Window: move to workspace left/right

hl.bind(mainMod .. "+ALT" .. " + " .. "Page_Down", hl.dsp.window.move({ workspace = "+1" }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. "Page_Up", hl.dsp.window.move({ workspace = -1 }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Page_Down", hl.dsp.window.move({ workspace = "r+1" }))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Page_Up", hl.dsp.window.move({ workspace = "r-1" }))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special" }, { follow = false }))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pin())

hl.bind("CTRL+" .. mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special(nil))

-- [hidden]

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

-- [hidden] sus keybind

-- TODO: manual review (unknown dispatcher: bringactivetotop)
-- hl.bind("ALT + Tab", hl.dsp.bring_to_top())

-- [hidden] bring it to the top

-- Testing

-- bind = mainModALT, f12, exec, notify-send "Hyprland version: $(hyprctl version | head -2 | tail -1 | cut -f2 -d ' ')" "owo" -a 'Hyprland keybind'

-- bind = mainMod+ALT, f12, exec, notify-send "Millis since epoch" "$(date +%s%N | cut -b1-13)" -a 'Hyprland keybind'

hl.bind(mainMod .. "+ALT" .. " + " .. "f12", hl.dsp.exec_cmd("notify-send 'Test notification' \"Here's a really long message to test truncation and wrapping\\nYou can middle click or flick this notification to dismiss it!\" -a 'Shell' -A \"Test1=I got it!\" -A \"Test2=Another action\" -t 5000"))

-- [hidden]

hl.bind(mainMod .. "+ALT" .. " + " .. "Equal", hl.dsp.exec_cmd("notify-send \"Urgent notification\" \"Ah hell no\" -u critical -a 'Hyprland keybind'"))

-- [hidden]

--#! Media

hl.bind(mainMod .. "+SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\" `"), { locked = true })

-- Next track

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media next"), { locked = true })

-- playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"` # [hidden]

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media previous"), { locked = true })

-- playerctl previous # [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Comma", hl.dsp.exec_cmd("~/.config/ags/scripts/music/adjust-volume.sh -0.03"), { locked = true })

-- Raise music volume

hl.bind(mainMod .. "+SHIFT" .. " + " .. "Period", hl.dsp.exec_cmd("~/.config/ags/scripts/music/adjust-volume.sh 0.03"), { locked = true })

-- Lower music volume

hl.bind(mainMod .. "+SHIFT+ALT" .. " + " .. "mouse:275", hl.dsp.exec_cmd("playerctl previous"))

-- [hidden]

hl.bind(mainMod .. "+SHIFT+ALT" .. " + " .. "mouse:276", hl.dsp.exec_cmd("playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\" `"))

-- [hidden]

hl.bind(mainMod .. "+SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Previous track

hl.bind(mainMod .. "+SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

-- Play/pause media

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media playPause"), { locked = true })

-- playerctl play-pause # [hidden]

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call media playPause"), { locked = true })

-- playerctl play-pause # [hidden]

--!

--#! Apps

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("code"))

-- Launch VSCode (editor)

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus --new-window"))

-- Launch Nautilus (file manager)

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("zen-browser"))

-- [hidden] Let's not give people (more) reason to shit on my rice

hl.bind("CTRL+" .. mainMod .. " + " .. "V", hl.dsp.exec_cmd("pavucontrol"))

-- Launch pavucontrol (volume mixer)

-- bind = mainMod, Super_L, exec, ~/.config/rofi/launcher.sh # App Launcher

hl.bind(mainMod .. " + " .. "Space", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))

-- Cursed stuff

--# Make window not amogus large


-- [hidden]