-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
    name  = "no_blur_on",
    match = {
        xwayland = 1,
    },
    no_blur = true,
    -- TODO: review rule: "no_blur on"
})

-- Floating

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(blueberry\\.py)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(steam)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(guifetch)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

-- FlafyDev/guifetch

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true

    -- TODO: review rule: "float on"
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(gui)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

-- Tiling

hl.window_rule({
    name  = "tile_on",
    match = {
        class = "^dev\\.warp\\.Warp$",
    },
    tile = true
    -- TODO: review rule: "tile on"
})

-- Picture-in-Picture

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    float = true
    -- TODO: review rule: "float on"
})

-- Dialog windows – float+center these windows.

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
})

-- --- Tearing ---

hl.window_rule({
    name  = "immediate_on",
    match = {
        title = [[.*\.exe]]
    },
    immediate = true,
    -- TODO: review rule: "immediate on"
})

hl.window_rule({
    name  = "immediate_on",
    match = {
        class = "^(steam_app)",
    },
    immediate = true
    -- TODO: review rule: "immediate on"
})

-- No shadow for tiled windows (matches windows that are not floating).

hl.window_rule({
    name  = "no_shadow_on",
    match = {
        float = 0,
    },
    no_shadow = true
    -- TODO: review rule: "no_shadow on"
})

-- open qemu in special

hl.window_rule({
    name  = "workspace_special",
    match = {
        title = "(QEMU)",
    },
    workspace = "special",
})

-- ######## Workspace rules ########

hl.workspace_rule({
    workspace = "special:special",
    gaps_out = 30,
})

-- ######## Layer rules ########

hl.layer_rule({
    match = {
        namespace = ".*",
    },
    xray = 1,
})

-- layerrule = noanim, .*

hl.layer_rule({
    match = {
        namespace = "walker",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "selection",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "overview",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "anyrun",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "indicator.*",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "osk",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "hyprpicker",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "noanim",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.69",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace logout_dialog",
    },
    blur = true,
})

-- wlogout
