windowrule = no_blur on, match:xwayland 1

# Floating
windowrule = float on, match:class ^(blueberry\.py)$
windowrule = float on, match:class ^(steam)$
windowrule = float on, match:class ^(guifetch)$   # FlafyDev/guifetch
windowrule = float on, size 45% 50%, center on, match:class ^(pavucontrol)$
windowrule = float on, size 45% 50%, center on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, size 45% 50%, center on, match:class ^(nm-connection-editor)$

windowrule = float on, move ((monitor_w*1)-window_w-) (0), no_initial_focus on, match:title ^(gui)$

# Tiling
windowrule = tile on, match:class ^dev\.warp\.Warp$

# Picture-in-Picture
windowrule = float on, keep_aspect_ratio on, move 73% 72%, size 25% 25%, pin on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

# Dialog windows – float+center these windows.
windowrule = center on, float on, match:title ^(Open File)(.*)$
windowrule = center on, float on, match:title ^(Select a File)(.*)$
windowrule = center on, float on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, float on, match:title ^(Open Folder)(.*)$
windowrule = center on, float on, match:title ^(Save As)(.*)$
windowrule = center on, float on, match:title ^(Library)(.*)$
windowrule = center on, float on, match:title ^(File Upload)(.*)$


# --- Tearing ---
windowrule = immediate on, match:title .*\.exe
windowrule = immediate on, match:class ^(steam_app)

# No shadow for tiled windows (matches windows that are not floating).
windowrule = no_shadow on, match:float 0

# open qemu in special
windowrule = workspace special, match:title (QEMU)

# ######## Workspace rules ########
workspace = special:special, gapsout:30


# ######## Layer rules ########
layerrule = xray 1, match:namespace .*
# layerrule = noanim, .*
layerrule = no_anim on, match:namespace walker
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace overview
layerrule = no_anim on, match:namespace anyrun
layerrule = no_anim on, match:namespace indicator.*
layerrule = no_anim on, match:namespace osk
layerrule = no_anim on, match:namespace hyprpicker

layerrule = no_anim on, match:namespace noanim
layerrule = blur on, ignore_alpha 0, match:namespace gtk-layer-shell
layerrule = blur on, ignore_alpha 0.5, match:namespace launcher
layerrule = blur on, ignore_alpha 0.69, match:namespace notifications
layerrule = blur on, match:namespace logout_dialog # wlogout
